# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    sort_pub_dependencies: false
    avoid_classes_with_only_static_members: false
    implementation_imports: false
    empty_catches: false